name: Deploy remote production project

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch production branch
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          username: root
          password: ${{ secrets.TEST_SERVER_SSH_KEY }}
          script: |
            cd /Garage
            git reset --hard HEAD
            git pull origin production
      - name: Rebuild && up containers
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          username: root
          password: ${{ secrets.TEST_SERVER_SSH_KEY }}
          script: |
            cd /Garage
            make remove
            make build
            make run
